### ISSUE TITLE
ratings

### ISSUE THREAD

**Issue by bob122249** [malaschitz/little-golem-doc#10]
would it be too much trouble to provide a table for kyu/dan ratings?

**Comment by malaschitz** [comment]
I will add it on https://docs.littlegolem.net/ratings/

**Comment by malaschitz** [comment]
Solved. There is a table on https://docs.littlegolem.net/ratings/

**Comment by bob122249** [comment]
very helpful! thanks a lot!
   
   
   
    On 05/26/2024 12:21 PM EDT Rio Malaschitz ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Solved. There is a table on https://docs.littlegolem.net/ratings/
